version: "3.3"
services:
  postDB:
    container_name: postDB
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./server/db/database.sql:/docker-entrypoint-initdb.d/create_tables.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    container_name: frontend
    build: ./frontend
    depends_on:
      - backend
    ports:
      - 127.0.0.1:5173:5173
    links:
     - backend

  backend:
    container_name: backend
    build: ./server
    ports:
      - 127.0.0.1:9808:9808
    links:
      - postDB
      - redisStore
    depends_on:
      postDB:
       condition: service_healthy

  redisStore:
    container_name: redisStore
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
