version: "3.3"
services:
  postDB:
    container_name: postDB
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./server/db/database.sql:/docker-entrypoint-initdb.d/create_tables.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    container_name: web
    build: ./frontend
    depends_on:
      - server
    ports:
      - 5173:5173
    links:
     - server

  server:
    container_name: server
    build: ./server
    ports:
      - 9808:9808
    links:
      - postDB
      - redisStore
      - redisUser
    depends_on:
      postDB:
       condition: service_healthy

  redisStore:
    container_name: redisStore
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  redisUser:
    container_name: redisUser
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
