version: "2.1"
services:
  postDB:
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${postPass}
    volumes:
      - ./server/db/database.sql:/docker-entrypoint-initdb.d/create_tables.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build: ./frontend
    depends_on:
      - backend
    links:
     - backend

  backend:
    build: ./server
    links:
      - postDB
      - redisStore
    depends_on:
      redisStore:
        condition: service_started
      postDB:
          condition: service_healthy

  redisStore:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=${redisStorePass}

  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 8000:8000
      - 8001:8001
      - 9808:9808
    depends_on:
      - frontend
      - backend