apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: postdb
  name: postdb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postdb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/bytez-default: "true"
        io.kompose.service: postdb
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              value: postgres
          image: postgres:latest
          livenessProbe:
            exec:
              command:
                - pg_isready -U postgres
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: postDB
          resources: {}
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/create_tables.sql
              name: postdb-claim0
      restartPolicy: Always
      volumes:
        - name: postdb-claim0
          persistentVolumeClaim:
            claimName: postdb-claim0
status: {}
