apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: redisstore
  name: redisstore
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redisstore
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/bytez-default: "true"
        io.kompose.service: redisstore
    spec:
      containers:
        - env:
            - name: REDIS_PASSWORD
          image: bitnami/redis:latest
          name: redisStore
          resources: {}
      restartPolicy: Always
status: {}
